### ISSUE TITLE
Update CONTRIBUTING.rst with additional workflow detail

### ISSUE THREAD

**Issue by micahjsmith** [HDI-Project/BTB#51]
Things to update
- Update all of the code snippets as necessary
    - instead of `python setup.py develop`, use `pip install -r requirements_dev.txt` followed by `pip install -e .`
    - delete the part about installing flake8 etc because it will be installed via `requirements_dev.txt`.
- Deployment section at bottom with details on making releases under git flow
- Under "implement features", add description of labels to apply to issues and snippet requesting to commit to master only via PRs w/ associated issues.

**Comment by csala** [comment]
I updated the `CONTRIBUTING.rst` file in branch [GH_51_update_contributing](https://github.com/HDI-Project/BTB/tree/GH_51_update_contributing.rst) to:

* Fix all the GitHub links to the project
* Update instructions about the creation of the development environment
* Add instructions and commands to run the tests and view the docs
* Update the PR guidelines to make the GitHub Issue a requirement
* Reword some sentences to reduce ambiguity

I will also include in a different commit some guidelines about how to properly write Unit Tests, as well as the pending explanations about the Github issue labels and the the release workflow.

**Comment by csala** [comment]
I updated the `CONTRIBUTING.rst` with Unit Test guidelines, but I was doubting whether to put the other two things here or not, since I think that they are things that mainly concern the repository administrators, and not the contributors.

So, should I put it there, or may we have a separated document for that? Indeed, if it is a separated document, it could even be excluded from the rendered Sphinx documentation.

**Comment by csala** [comment]
Closed via #58 and #72
